char_map = {  # you need to add 0x
    "61": "a",  # smol letters
    "62": "b",
    "63": "c",
    "64": "d",
    "65": "e",
    "66": "f",
    "67": "g",
    "68": "h",
    "69": "i",
    "6a": "j",
    "6b": "k",
    "6c": "l",
    "6d": "m",
    "6e": "n",
    "6f": "o",
    "70": "p",
    "71": "q",
    "72": "r",
    "73": "s",
    "74": "t",
    "75": "u",
    "76": "v",
    "77": "w",
    "78": "x",
    "79": "y",
    "7a": "z",
    "41": "A",  # capital letters
    "42": "B",
    "43": "C",
    "44": "D",
    "45": "E",
    "46": "F",
    "47": "G",
    "48": "H",
    "49": "I",
    "4a": "J",
    "4b": "K",
    "4c": "L",
    "4d": "M",
    "4e": "N",
    "4f": "O",
    "50": "P",
    "51": "Q",
    "52": "R",
    "53": "S",
    "54": "T",
    "55": "U",
    "56": "V",
    "57": "W",
    "58": "X",
    "59": "Y",
    "5a": "Z",
    "31": "1",  # numbers
    "32": "2",
    "33": "3",
    "34": "4",
    "35": "5",
    "36": "6",
    "37": "7",
    "38": "8",
    "39": "9",
    "30": "0",
    "60": "`",  # specials
    "2d": "-",
    "5f": "_",
    "3d": "=",
    "2b": "+",
    "5b": "[",
    "5d": "]",
    "5c": "\\",  # Never gonna give you up
    "2f": "/",  # Never gonna let you down
    "2e": ".",  # Never gonna run around and desert you
    "2c": ",",  # Never gonna make you cry
    "27": "'",  # Never gonna say goodbye
    "3b": ";",  # Never gonna tell a lie and hurt you
    "7b": "{",
    "7d": "}",
    "22": '"',
    "3a": ":",
    "7c": "|",
    "3f": "?",
    "3e": ">",
    "3c": "<",
    "1b": "alt", 
    "20": " ",
    "a": "enter",
    "9": "tab",
    "7e": "~",
    "21": "!",
    "40": "@",
    "23": "#",
    "24": "$",
    "25": "%",
    "5e": "^",
    "26": "&",
    "2a": "*",
    "28": "(",
    "29": ")",
    "41l": "up",  # hacky fix to namechake with capital ABCD
    "42l": "down",
    "43l": "right",
    "44l": "left",
    "7f": "bck",
    "31l": "home",
    "34l": "end",
    "35l": "pgup",
    "36l": "pgdw",
    "33l": "del",
    "32l": "ins",
    "ctrlC": "ctrlC",  # Ctrl combs
    "4": "ctrlD",
    "18": "ctrlX",
    "6": "ctrlF",
    "7": "ctrlG",
    "8": "ctrlH",
    "b": "ctrlK",
    "17": "ctrlW",
    "5": "ctrlE",
    "12": "ctrlR"
}
