class lJ_Colours:
    """
    Placebo for those who want to disable lJ_Colours
    """

    okay = ""
    warning = ""
    error = ""
    underline = ""
    bold = ""
    endc = ""
    okblue = ""
    okcyan = ""
    reset_s_format = ""
    black_t = ""
    red_t = ""
    green_t = ""
    yellow_t = ""
    blue_t = ""
    magenta_t = ""
    cyan_t = ""
    white_t = ""
